"""initial schema

Revision ID: c5aad791929d
Revises: 
Create Date: 2026-08-16 08:56:06.748011

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5aad791929d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('filing_type', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_accession_number'), 'source_documents', ['accession_number'], unique=True)
    op.create_index(op.f('ix_source_documents_filing_type'), 'source_documents', ['filing_type'], unique=False)
    op.create_index(op.f('ix_source_documents_ticker'), 'source_documents', ['ticker'], unique=False)
    op.create_index('ix_source_documents_ticker_year', 'source_documents', ['ticker', 'year'], unique=False)
    op.create_index(op.f('ix_source_documents_year'), 'source_documents', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=64), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', chunk_text)", persisted=True), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_document_index', 'document_chunks', ['document_id', 'chunk_index'], unique=True)
    # HNSW index for approximate vector similarity search (cosine).
    op.execute(
        "CREATE INDEX ix_document_chunks_embedding_hnsw "
        "ON document_chunks USING hnsw (embedding vector_cosine_ops)"
    )
    # GIN index for Postgres full-text search on the generated tsvector column.
    op.execute(
        "CREATE INDEX ix_document_chunks_search_vector_gin "
        "ON document_chunks USING gin (search_vector)"
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('message_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_index('ix_chat_messages_thread_sequence', 'chat_messages', ['thread_id', 'sequence_number'], unique=True)
    op.create_table('message_citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_citations_message_id'), 'message_citations', ['message_id'], unique=False)
    # ### end Alembic commands ###

    # Row-level security: users only reach their own rows; corpus tables are
    # readable by any authenticated user. The service role bypasses RLS.
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY users_select_own ON users "
        "FOR SELECT USING (id = auth.uid())"
    )

    op.execute("ALTER TABLE source_documents ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY source_documents_select_auth ON source_documents "
        "FOR SELECT TO authenticated USING (true)"
    )

    op.execute("ALTER TABLE document_chunks ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY document_chunks_select_auth ON document_chunks "
        "FOR SELECT TO authenticated USING (true)"
    )

    op.execute("ALTER TABLE chat_threads ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY chat_threads_user_all ON chat_threads "
        "USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid())"
    )

    op.execute("ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY chat_messages_own ON chat_messages "
        "USING (thread_id IN (SELECT id FROM chat_threads WHERE user_id = auth.uid())) "
        "WITH CHECK (thread_id IN (SELECT id FROM chat_threads WHERE user_id = auth.uid()))"
    )

    op.execute("ALTER TABLE message_citations ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY message_citations_own ON message_citations "
        "USING (message_id IN ("
        "  SELECT m.id FROM chat_messages m "
        "  JOIN chat_threads t ON t.id = m.thread_id "
        "  WHERE t.user_id = auth.uid())) "
        "WITH CHECK (message_id IN ("
        "  SELECT m.id FROM chat_messages m "
        "  JOIN chat_threads t ON t.id = m.thread_id "
        "  WHERE t.user_id = auth.uid()))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS message_citations_own ON message_citations")
    op.execute("DROP POLICY IF EXISTS chat_messages_own ON chat_messages")
    op.execute("DROP POLICY IF EXISTS chat_threads_user_all ON chat_threads")
    op.execute("DROP POLICY IF EXISTS document_chunks_select_auth ON document_chunks")
    op.execute("DROP POLICY IF EXISTS source_documents_select_auth ON source_documents")
    op.execute("DROP POLICY IF EXISTS users_select_own ON users")
    op.execute("ALTER TABLE message_citations DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE chat_messages DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE chat_threads DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE document_chunks DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE source_documents DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY")
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_search_vector_gin")
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_citations_message_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_index('ix_chat_messages_thread_sequence', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_document_chunks_document_index', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_documents_year'), table_name='source_documents')
    op.drop_index('ix_source_documents_ticker_year', table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_ticker'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_filing_type'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_accession_number'), table_name='source_documents')
    op.drop_table('source_documents')
    # ### end Alembic commands ###
